config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "news#index"

  resources :news do
    member do
      post 'remove_news'
    end
    collection do
      get 'read_list'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :users_news
end

app/models/users_news.rb
class UsersNews < ApplicationRecord
  belongs_to :user
  belongs_to :news

  enum status: [:read, :removed]

  #Scopes
  scope :removed_news, -> {where(status: "removed")}
  scope :read_news, -> {where(status: "read")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

    def index
        if user_signed_in?
            removed_ids = current_user.users_news.removed_news.pluck(:news_id)
            @news = News.where.not(id: removed_ids)
        else
            @news = News.all
        end
    end

    def show
        if user_signed_in?
            unless UsersNews.find_by_user_id_and_news_id(current_user.id,params[:id])
                UsersNews.create(user_id: current_user.id, news_id: params[:id],status: :read)
            end
        end
        @news = News.find(params[:id])
    end

    def remove_news
        if UsersNews.find_by_user_id_and_news_id(current_user.id,params[:id])
            user_news = UsersNews.find_by_user_id_and_news_id(current_user.id,params[:id])
            user_news.update_attributes(status: :removed)
        else
            UsersNews.create(user_id: current_user.id, news_id: params[:id],status: :removed)
        end
        redirect_to news_index_path
    end

    def read_list
        read_ids = current_user.users_news.read_news.pluck(:news_id)
        @news = News.where(id: read_ids)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/layouts/_header.html.erb
<div class="header-div">
    <span><%= link_to news_index_path do %> All news <%end%></span>
    <%if user_signed_in? %>
        <span><%= link_to  read_list_news_index_path  do %>Read news<%end%></span>
    <%end%>
    <span><%unless user_signed_in? %><%= link_to "Sign in", new_user_session_path %><%end%></span>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShaadisagaChallange</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/news/_news_list.html.erb
<div>
    <%@news.each do |news| %>
        <div class="bordered-div">

            <% if user_signed_in? %>
                <div style="text-align: end;"><%= link_to "Delete", remove_news_news_path(news.id), method: "post" %></div>
            <%end%>

            <p><%= link_to news_path(news.id) do %><strong>Title:</strong> <%= news.title %><%end%></p>
            <p><strong>Description:</strong> <%= news.description[0..50] %>..</p>
        </div>
    <%end%>
</div>

app/views/news/index.html.erb
<%= render "news_list" %>

app/views/news/read_list.html.erb
<%= render "news_list" %>

app/views/news/show.html.erb
<div>
    <p>
        <strong>Title: </strong> <%= @news.title %>
    </p>
    <p><%= @news.description %></p>
</div>